<html>
<head>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
</head>
<body>
    <header class="header">
        <div>
            <a href="/#" style='color: red;'> <h1 class='Title_web'>Trung blog </h1> </a> 
            <div class='sign'>
                <a href="http://trungtrung.com/signin.php"> <img class='login' src="static/Mushroom - 1UP.ico" /> </a>
            </div>
        </div>
    </header>